version: '3.8'

services: 
  db:
    image: mysql:5.7
    container_name: invoicy_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoicy_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: invoicy_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

  maildev:
    image: maildev/maildev
    container_name: invoicy_maildev
    command: bin/maildev --web 80 --smtp 1025 --hide-extensions STARTTLS
    ports:
      - 1080:80
      - 1025:25
    restart: always

  backend:
    build:
      context: ./backend
    container_name: invoicy_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/invoicy_db

  # ai:
  #   build: ./ai-facturation
  #   container_name: ai-facturation
  #   volumes:
  #     - ./ai-facturation:/var/wwww/ai
  #   depends_on:
  #     - backend

  frontend:
    build:
      context: ./frontend
    container_name: invoicy_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend


volumes:
  db_data: