api_platform:
    title: Invoicy API
    description: API sécurisée pour la gestion des factures
    version: 1.0.0
    show_webby: false

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
