security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        cors_preflight:  # <<< Ce bloc doit être en premier !
            pattern: ^/api/
            methods: [OPTIONS]
            security: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Authentification via ton custom authenticator
        api_login:
            pattern: ^/api/login
            stateless: true
            custom_authenticator: App\Security\Login\LoginAuthenticator
            provider: app_user_provider

        # Le reste des routes API protégées par JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            provider: app_user_provider

        main:
            lazy: true
            provider: app_user_provider

    role_hierarchy:
        ROLE_PUBLIC: [PUBLIC_ACCESS ]
        ROLE_USER: [ROLE_PUBLIC]
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles:  IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/register, roles:  IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/profile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/api/verif, roles:  IS_AUTHENTICATED_ANONYMOUSLY}
